# Generated by Django 5.0.2 on 2024-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agriculture_Call_centre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("detail", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="Call Centre")),
            ],
        ),
        migrations.CreateModel(
            name="Agriculture_Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="Crop")),
                ("description", models.TextField()),
                ("video", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Agriculture_Framer_Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("pdf", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Agriculture_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Agriculture_Universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("establis", models.CharField(max_length=5)),
                ("director", models.CharField(max_length=30)),
                ("image", models.ImageField(blank=True, upload_to="University")),
                ("address", models.CharField(max_length=100, null=True)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Agriculture_Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("video", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Indian_Agriculture_University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="Indian University")),
                ("city", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Latest_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("photo", models.ImageField(blank=True, upload_to="Technology")),
                ("description", models.TextField()),
            ],
        ),
    ]
