# Generated by Django 5.0.2 on 2024-02-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_agriculture_call_centre_agriculture_crop_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agriculture_universities",
            old_name="establis",
            new_name="established",
        ),
    ]
