# Generated by Django 5.0.2 on 2024-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_establis_agriculture_universities_established"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indian_agriculture_university",
            name="city",
        ),
        migrations.RemoveField(
            model_name="indian_agriculture_university",
            name="description",
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="address_is",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="director_is",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="established_in",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="indian_agriculture_university",
            name="website_is",
            field=models.URLField(null=True),
        ),
    ]
