# Generated by Django 5.0.2 on 2024-02-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_indian_agriculture_university_city_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Agriculture_Framer_Scheme",
            new_name="Agriculture_Farmer_Scheme",
        ),
    ]
