# Generated by Django 5.0.2 on 2024-02-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_agriculture_framer_scheme_agriculture_farmer_scheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="myreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("message", models.TextField()),
            ],
        ),
    ]
