# Generated by Django 5.0.2 on 2024-02-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_register_address_register_age_register_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
