# Generated by Django 5.0.2 on 2024-02-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_register_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="agri_crops_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=50)),
                ("crop_head", models.CharField(max_length=50)),
                ("image1", models.ImageField(blank=True, upload_to="Crop")),
                ("image2", models.ImageField(blank=True, upload_to="Crop")),
                ("para1", models.TextField()),
                ("para2", models.TextField()),
                ("para3", models.TextField()),
            ],
        ),
    ]
