# Generated by Django 5.0.2 on 2024-02-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_agri_crops_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agri_crops_details",
            name="crop_type",
        ),
        migrations.AddField(
            model_name="agri_crops_details",
            name="crop_identity",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="agriculture_crop",
            name="crop_identity",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
