# Generated by Django 5.0.2 on 2024-02-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_remove_agri_crops_details_crop_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agri_crops_details",
            name="pdf",
            field=models.FileField(blank=True, upload_to="crop_pdf"),
        ),
    ]
