# Generated by Django 5.0.2 on 2024-02-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_agri_crops_details_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculture_news",
            name="image",
            field=models.ImageField(blank=True, upload_to="News"),
        ),
    ]
