# Generated by Django 5.0.2 on 2024-02-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_agriculture_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculture_news",
            name="reporter",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
