# Generated by Django 5.0.2 on 2024-02-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_agriculture_news_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculture_news",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
