# Generated by Django 5.0.2 on 2024-02-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_agriculture_news_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculture_news",
            name="photographer",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
