# Generated by Django 5.0.2 on 2024-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_agriculture_news_date_agriculture_news_sub_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agri_crops_details",
            name="crop_head",
            field=models.CharField(max_length=100),
        ),
    ]
