# Generated by Django 5.0.2 on 2024-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_agri_crops_details_crop_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="disease_solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("detail", models.TextField()),
            ],
        ),
    ]
