# Generated by Django 5.0.2 on 2024-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_disease_solution"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease_solution",
            name="disease",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
