# Generated by Django 5.0.2 on 2024-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_disease_solution_disease"),
    ]

    operations = [
        migrations.CreateModel(
            name="support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
