# Generated by Django 5.0.2 on 2024-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="ProfilePictures"),
        ),
    ]
