# Generated by Django 5.0.2 on 2024-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static\\images\\signin-image.jpg",
                upload_to="ProfilePictures",
            ),
        ),
    ]
