# Generated by Django 5.0.2 on 2024-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_alter_register_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="media\\ProfilePictures\\PotatoEarlyBlight5_ssW0nil.jpeg",
                upload_to="ProfilePictures",
            ),
        ),
    ]
