# Generated by Django 5.0.2 on 2024-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_alter_register_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="latest_technology",
            name="pdf",
            field=models.FileField(blank=True, upload_to="Technology"),
        ),
    ]
