# Generated by Django 5.0.2 on 2024-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_latest_technology_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="dealers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(max_length=100)),
                ("website", models.URLField(null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="Dealers (Pesticide | Fetilizer)"
                    ),
                ),
            ],
        ),
    ]
